name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 120
        days-before-close: 14
        stale-issue-message: 'This issue is stale for 100+ days, so it will be closed in 14 more days'
        stale-pr-message: 'This issue is stale for 100+ days, so it will be closed in 14 more days'
        stale-issue-label: "Status: stale"
        stale-pr-label: "Status: stale"
